"""Add invite_code_hash to Company

Revision ID: 68c25c53765b
Revises: '926d3f34ebd2'
Create Date: 2026-09-15 21:09:09.465460

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '68c25c53765b'
down_revision: Union[str, None] = '926d3f34ebd2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('invite_code_hash', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('companies', 'invite_code_hash')
    # ### end Alembic commands ###
