"""change_file_path_to_file_data_longblob

Revision ID: a130d327e53d
Revises: '68c25c53765b'
Create Date: 2026-09-15 21:48:29.130848

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'a130d327e53d'
down_revision: Union[str, None] = '68c25c53765b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('file_data', mysql.LONGBLOB(), nullable=True))
    op.drop_column('documents', 'file_path')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('file_path', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=512), nullable=True))
    op.drop_column('documents', 'file_data')
    # ### end Alembic commands ###
